### ISSUE TITLE
The prices are so expensive

### ISSUE THREAD

**Issue by incleaf** [yangroro/hongkong-travel-2016#1]
http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=104&oid=014&aid=0003565186

**Comment by kyeongwan** [comment]
That`s ok, because we have no money.

**Comment by yangroro** [comment]
we don't care about money

**Comment by kyeongwan** [comment]
GOD roro

**Comment by yangroro** [comment]
@kyeongwan I have enough money. But, you don't

**Comment by kyeongwan** [comment]
Thank you for the meal.

**Comment by kyeongwan** [comment]
That you are buying me

**Comment by incleaf** [comment]
HEEEEEEEEEEK CHAN!

**Comment by yangroro** [comment]
@kyeongwan @incleaf Your suggestion won't  be reflected

**Comment by incleaf** [comment]
What a bad heekchuation;;

**Comment by yangroro** [comment]
@incleaf sorry, but it was decided 2month ago
